workflow_files: &workflow_files
  - ".github/workflows/*.yml"
  - ".github/file-filters.yml"

project_config: &project_config
  - "{package,package-lock}.json"

common_site_libs: &common_site_libs
  - "**/common/**/*.[tj]{s,sx}"

site_dependencies: &site_dependencies
  - *workflow_files
  - *common_site_libs
  - *project_config

echo: &echo
  - *site_dependencies
  - "**/sites/echo/**/*.[tj]{s,sx}"

acme: &acme
  - *site_dependencies
  - "**/sites/acme/**/*.[tj]{s,sx}"
