name: acme
on:
  push:
    branches-ignore:
      - "wip/**"
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  files-changed:
    name: detect file changes
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      site-changed: ${{ steps.changes.outputs.acme }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: .github/file-filters.yml
          list-files: "json"

  sonarqube:
    name: code analysis
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: debug vars
        run: |
          echo "Github Event Name: ${{ github.event_name }}"
          echo "Site Changed: ${{ needs.files-changed.outputs.site-changed }}"
      - name: setup env var
        run: |
          echo "export SITE_CHANGED=${{ needs.files-changed.outputs.site-changed }}" >> $GITHUB_ENV

  test:
    name: run tests
    if: |
      (
        ${{ github.event_name == 'pull_request'}} ||
        ${{ github.event_name == 'push'}} ||
        ${{ github.event_name == 'workflow_dispatch'}}
      ) &&
      ${{ env.SITE_CHANGED == 'true' }}
    needs: sonarqube
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: debug vars
        run: |
          echo "Github Event Name: ${{ github.event_name }}"
          echo "Site Changed: ${{ env.SITE_CHANGED }}"
      - run: echo "running tests"

  build:
    name: run build
    needs: sonarqube
    if: |
      (
        ${{ github.event_name == 'pull_request'}} ||
        ${{ github.event_name == 'push'}} ||
        ${{ github.event_name == 'workflow_dispatch'}}
      ) &&
      ${{ env.SITE_CHANGED == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: debug vars
        run: |
          echo "Github Event Name: ${{ github.event_name }}"
      - run: echo "running build"
      - run: |
          mkdir -pv src/sites/acme/dist
          echo '{"site": "acme"}' > src/sites/acme/dist/outbound.js
      - uses: actions/upload-artifact@v4
        with:
          path: src/sites/acme/dist/outbound.js
          compression-level: 0
          if-no-files-found: error

  deploy-testing-interfaces:
    name: deploy testing interfaces
    environment: staging
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: debug vars
        run: |
          echo "Github Event Name: ${{ github.event_name }}"
      - uses: actions/download-artifact@v4
      - run: echo "running deploy-testing-interfaces"
