name: acme
on:
  push:
    branches-ignore:
      - 'wip/**'
  workflow_dispatch:

jobs:
  files-changed:
    name: detect file changes
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      site-changed: ${{ steps.changes.outputs.acme }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: .github/file-filters.yml
          list-files: "json"

  sonarqube:
    name: code analysis
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

  test:
    name: run tests
    if: |
      ${{ github.event_name == 'pull_request'}} &&
      needs.files-changed.outputs.site-changed == 'true'
    needs: sonarqube
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "running tests"
