name: acme
on:
  push:
    branches-ignore:
      - 'wip/**'
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  files-changed:
    name: detect file changes
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      site-changed: ${{ steps.changes.outputs.acme }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: .github/file-filters.yml
          list-files: "json"

  sonarqube:
    name: code analysis
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: debug vars
        run: |
          echo "Github Event Name: ${{ github.event_name }}"
          echo "Site Changed: ${{ needs.files-changed.outputs.site-changed }}"

  test:
    name: run tests
    if: |
      ${{ github.event_name == 'pull_request'}} &&
      needs.files-changed.outputs.site-changed == 'true'
    needs: sonarqube
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: debug vars
        run: |
          echo "Github Event Name: ${{ github.event_name }}"
          echo "Site Changed: ${{ needs.files-changed.outputs.site-changed }}"
      - run: echo "running tests"

  build:
    name: run build
    needs: sonarqube
    if: |
      ${{ github.event_name != 'pull_request'}} &&
      needs.files-changed.outputs.site-changed == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: debug vars
        run: |
          echo "Github Event Name: ${{ github.event_name }}"
          echo "Site Changed: ${{ needs.files-changed.outputs.site-changed }}"
      - run: echo "running build"
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ env.site }}-*.tgz
          compression-level: 0
          if-no-files-found: error

  deploy-testing-interfaces:
    name: deploy testing interfaces
    environment: staging
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: debug vars
        run: |
          echo "Github Event Name: ${{ github.event_name }}"
          echo "Site Changed: ${{ needs.files-changed.outputs.site-changed }}"
      - uses: actions/download-artifact@v4
      - run: echo "running deploy-testing-interfaces"
